apiVersion: v1
kind: Pod
metadata:
  name: taint
  labels:
    purpose: taint-demo
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b # Pod will be scheduled only on nodes in this zone
  tolerations: # Allow scheduling on nodes with matching taints
    - key: "hardware"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
    - key: "hardware"
      operator: "Equal"
      value: "gpu"
      effect: "NoExecute"
  containers:
    - name: nginx
      image: nginx
